### ISSUE TITLE
mvn findbugs:finbugs fails on robot-service module

### ISSUE THREAD

**Issue by ghost** [G-SHOCK-TEAM/G-SHOCK-TEAM-robot#12]
There is a stack trace:

Please re-run: mvn findbugs:finbugs -e

**Comment by danone771909** [comment]
We already coped with this. Thank You for great Issue :+1:

**Comment by KPP13** [comment]
I have already fixed it.

**Comment by KPP13** [comment]
Reopen - still sth is wrong :P

**Comment by KPP13** [comment]
Ok, everything is OK now - you have to run 'mvn install' to install the .war in local repository.
