### ISSUE TITLE
Zmieńcie nazwę proszę

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [G-SHOCK-TEAM/G-SHOCK-TEAM-robot#8]
By w raportach nie było kilku robotów, ale by nazwa odwoływała się do lidera lub zespołu, bym wiedział czyje to. :-)

**Comment by LIttleAncientForestKami** [comment]
Still doesn't work. Please verify that name is same in all places. :-)

**Comment by danone771909** [comment]
Naprawione :+1:
